unit Unit7;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls, FileCtrl, Grids, Outline, DirOutln;

type
  TForm7 = class(TForm)
    DirectoryOutline1: TDirectoryOutline;
    DriveComboBox1: TDriveComboBox;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form7: TForm7;

implementation

{$R *.DFM}

end.
